data_paths:
  train_val_test: data/BTCUSD_Hourly_Ask_2022.01.01_2024.07.01.csv
  finetune: data/new_data.csv

model_params:
  input_size: 19
  hidden_size: 19
  num_layers: 2

training_params:
  num_epochs: 2
  learning_rate: 0.001
  patience: 30
  batch_size: 128

finetuning_params:
  num_epochs: 50
  learning_rate: 0.0001
  patience: 15